### ISSUE TITLE
There is not "model" file on the folder results when running "3_PCA_SINDy.sh"

### ISSUE THREAD

**Issue by munozdjp** [pvlachas/LearningEffectiveDynamics#2]
Hello, I hope you're doing well. I was attempting to reproduce the results of your paper using the file 3_PCA_RNN.sh, but I encountered an error. It appears that the 'model' file is not being created and as a result, I am getting the following error message:

ValueError: [Errno 2] No such file or directory: '/home/munozdjp/Documents/LED-Juan_Ibex/Code/Results/FHN/Trained_Models/GPU-RNN-DimRed-scaler_MinMaxZeroOne-METHOD_pca-LD_6-OPT_adabelief-C_lstm-R_1x16-SL_40-LR_0.01/model'

Would you be able to provide any assistance or guidance on how I can resolve this issue? Thank you.

**Comment by munozdjp** [comment]
I think you need to add a comment in the file "3_PCA_RNN.sh" on line `55`.

**Comment by pvlachas** [comment]
indeed.
